// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Vx3860ijWR3I3hq_6vPi9PVs4jIkkE0',
    appId: '1:510671207029:web:e09ac9e509881c1ef7d63c',
    messagingSenderId: '510671207029',
    projectId: 'movies-ed953',
    authDomain: 'movies-ed953.firebaseapp.com',
    storageBucket: 'movies-ed953.firebasestorage.app',
    measurementId: 'G-9QXJ5LC3LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZLgOql-vZtVxJCWetE5mNkauCn2Gklvk',
    appId: '1:510671207029:android:7032025018d9c14af7d63c',
    messagingSenderId: '510671207029',
    projectId: 'movies-ed953',
    storageBucket: 'movies-ed953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFgYS8x1XVW4do2T2EF4rFNGfdibMV-Pg',
    appId: '1:510671207029:ios:ee2b6eeeef749a15f7d63c',
    messagingSenderId: '510671207029',
    projectId: 'movies-ed953',
    storageBucket: 'movies-ed953.firebasestorage.app',
    iosClientId: '510671207029-f6enjkqafd2lgsaql9bn4mv4hsnd5iu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

}